# Kafka Configuration for Local Development
# Based on Bitnami Kafka Chart

# Global settings
global:
  imageRegistry: ""
  imagePullSecrets: []

# Kafka cluster configuration
controller:
  replicaCount: 1
  
# Kafka broker configuration  
broker:
  replicaCount: 1
  
# Resource settings for local development
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

# Persistence settings
persistence:
  enabled: true
  size: 8Gi
  storageClass: ""

# Service configuration
service:
  type: ClusterIP
  ports:
    client: 9092
    
# External access configuration (for local development)
externalAccess:
  enabled: false
  
# Metrics configuration
metrics:
  kafka:
    enabled: true
  jmx:
    enabled: true
    
# Zookeeper configuration (if needed)
zookeeper:
  enabled: true
  persistence:
    enabled: true
    size: 8Gi
    
# Security settings
auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  
# Logging
logLevel: INFO

# JVM settings for local development
heapOpts: "-Xmx512m -Xms512m" 