# Kafka Production Configuration Template
# NOTE: This is a template - adjust values based on your production requirements

# === CORE KAFKA SETTINGS ===
controller:
  replicaCount: 3                    # 3 controllers for HA
  
broker:
  replicaCount: 3                    # 3 brokers for HA

# === RESOURCE ALLOCATION ===
controller:
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 4Gi
      cpu: 2000m
      
broker:
  resources:
    requests:
      memory: 4Gi
      cpu: 2000m
    limits:
      memory: 8Gi
      cpu: 4000m

# === PERSISTENCE ===
controller:
  persistence:
    enabled: true
    size: 100Gi
    storageClass: "fast-ssd"         # Use high-performance storage
    
broker:
  persistence:
    enabled: true
    size: 500Gi
    storageClass: "fast-ssd"

# === AUTHENTICATION ===
auth:
  clientProtocol: sasl_ssl           # Secure authentication
  interBrokerProtocol: sasl_ssl
  sasl:
    enabledMechanisms: "SCRAM-SHA-256,SCRAM-SHA-512"
    interBrokerMechanism: "SCRAM-SHA-512"
  tls:
    type: jks
    existingSecret: "kafka-tls-secret"

# === EXTERNAL ACCESS ===
externalAccess:
  enabled: true
  service:
    type: LoadBalancer
  autoDiscovery:
    enabled: true

# === METRICS & MONITORING ===
metrics:
  kafka:
    enabled: true
  jmx:
    enabled: true
    service:
      port: 5555

# === PROVISIONING ===
provisioning:
  enabled: true
  numPartitions: 3
  defaultReplicationFactor: 3
  
# === KRAFT MODE ===
kraft:
  enabled: true                      # Use KRaft mode (no Zookeeper)

# === HIGH AVAILABILITY ===
podDisruptionBudget:
  create: true
  minAvailable: 1

# === ANTI-AFFINITY ===
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - kafka
        topologyKey: kubernetes.io/hostname

# === JVM SETTINGS ===
heapOpts: "-Xmx3g -Xms3g"           # Larger heap for production 